nba_scores: data/naturalistic_data/nba_data_2000-2025.csv
market_data: data/naturalistic_data/market_data/snp.csv
lottery_data: data/naturalistic_data/mega_millions_processed.csv
billboard_100: data/naturalistic_data/billboard_100_2000-2025.csv
