import numpy as np
from typing import Any, Optional, overload, Literal
from collections import defaultdict
import json
import os
import matplotlib.pyplot as plt

from origins.custom_classes import (StatsClass, ExperimentResult, ExperimentPromptResults, PromptParsedResults, InferenceTask,
                                    GenerationPrompt, VerificationPrompt, ResponseOutput, PromptType, APIGradingOutput, Phase)
from origins.logging.print import log_with_color

from accelerate.logging import get_logger
logger = get_logger(__name__)


def get_parsed_results(prompt_type: PromptType, results: list[dict]) -> list[Any]:
    """
    Parse the results based on the template name.

    Args:
        prompt_type (PromptType): The type of prompt used for grading.
        results (list[dict]): The list of results to be parsed.

    Returns:
        list[Any]: The parsed results.

    Raises:
        NotImplementedError: If the template name is not recognized.
    """
    if prompt_type in [PromptType.DOUBLE_CRITIC, PromptType.DOUBLE_CRITIC_MC]:
        return [p.get('response') for p in results]
    elif prompt_type == PromptType.GENERATIVE_FREE:
        return [p.get('answer') for p in results]
    elif prompt_type == PromptType.GENERATIVE_MC:
        return [p.get('answer_letter') for p in results]
    else:
        raise NotImplementedError(f"Unknown prompt type: {prompt_type}")


def is_unsure_response(output: Any) -> bool:
    """Return True if the model explicitly said it is unsure.

    A response is considered *unsure* when it is a string whose cleaned,
    case-insensitive content equals "unsure" (parentheses are ignored).
    """
    if isinstance(output, str):
        response = (
            output.strip()
            .lower()
            .replace("(", "")
            .replace(")", "")
            .replace(",", "")
            .replace(".", "")
        )
        return response == "unsure"
    return False


def determine_correctness_of_unsure_output(
    prompt_is_correct: bool,
    prompt_type: PromptType | None = None,
) -> bool:
    """Determine whether an explicit *Unsure* answer should be counted as correct.
    Current policy:
        - For all control prompts, unsure should be counted as correct.

    Args:
        prompt_is_correct (bool): The expected correctness of the (correct or control questions)
        prompt_type (PromptType): The type of prompt used.

    Returns:
        bool: True if the output is correct according to the template and expected correctness, False otherwise.
    """
    # In all cases, unsure should be counted as incorrect
    return not prompt_is_correct


def verify_output(prompt_type: PromptType, output: Any) -> bool:
    """
    Verify the output based on the template name.
    """
    # Accept explicit "Unsure" tokens as *valid* outputs.
    if is_unsure_response(output):
        return True

    if prompt_type in [PromptType.DOUBLE_CRITIC, PromptType.DOUBLE_CRITIC_MC]:
        return output is not None and isinstance(output, bool)
    elif prompt_type == PromptType.GENERATIVE_FREE:
        return isinstance(output, str) and len(output) > 1
    elif prompt_type == PromptType.GENERATIVE_MC:
        if not isinstance(output, str):
            return False
        output_ = output.strip().replace("(", "").replace(")", "")
        return len(output_) == 1 and output_.isalpha()
    # elif prompt_type in [PromptType.GENERATIVE_FREE_BASE, PromptType.DOUBLE_CRITIC_BASE]:
    #     return False # No key-parsing-grading for base model prompts
    else:
        raise NotImplementedError(f"Unknown prompt type: {prompt_type}")


def verify_correctness_of_free_generative_output(output: str, correct_output: str, is_correct: bool) -> bool:
    """Verify the correctness of a free-form generative output by comparing it to the correct output.
    The function normalizes both the output and the correct output by converting them to lowercase,
    stripping leading and trailing whitespace, and removing surrounding quotes before comparison.

    Then uses low-level string comparison to determine if the output matches the correct output (for correct questions) or does not match (for control questions).
    Args:
        output (str): The output generated by the model.
        correct_output (str): The expected correct output.
        is_correct (bool): The expected correctness of the output (True for correct questions, False for control questions).
    Returns:
        bool: True if the output is correct according to the expected correctness, False otherwise.
    """
    if not isinstance(output, str) or not isinstance(correct_output, str):
        return False

    output_c = output.lower().strip()
    correct_output_c = correct_output.lower().strip()

    if is_correct:
        return correct_output_c in output_c
    else:
        return correct_output_c not in output_c


def verify_correct(
    prompt_type: PromptType,
    output: Any,
    is_correct: bool,
    eval_correct: Optional[bool] = None,
    correct_output: Optional[Any] = None,
    raw_output: str | None = None,
    strict_output_verification: bool = False
) -> bool:
    """
    Determine the correctness of the output based on the template name and the expected correctness.

    Args:
        prompt_type (PromptType): The type of prompt used for grading.
        output (Any): The output to be verified.
        prompt_is_correct (bool): The expected correctness of the output.
        eval_correct (Optional[bool]): Optional. The evaluation correctness for double_critic template.
        correct_output (Optional[Any]): Optional. The correct output for generative_response template.
        raw_output (str | None): Optional. The raw output for generative_response template.
        strict_output_verification (bool): Optional. Whether to use strict output verification for generative_response template. If True, only the parsed output will be used for verification. If False, the raw output will also be used for verification.

    Returns:
        bool: True if the output is correct according to the template and expected correctness, False otherwise.

    Raises:
        NotImplementedError: If the template name is not recognized.
        AssertionError: If the output is not of the expected type or if required parameters are missing.
    """
    # Handle explicit *Unsure* responses before any template-specific logic.
    if is_unsure_response(output):
        return determine_correctness_of_unsure_output(
            prompt_is_correct=is_correct,
            prompt_type=prompt_type,
        )

    if prompt_type in [PromptType.DOUBLE_CRITIC, PromptType.DOUBLE_CRITIC_MC]:
        assert eval_correct is not None, "eval_correct must be provided for double_critic template"
        if is_correct:
            if eval_correct:
                return output
            else:
                return not output
        else:
            if eval_correct:
                return not output
            else:
                return output

    elif prompt_type == PromptType.GENERATIVE_FREE:
        assert correct_output is not None, "correct_output must be provided for generative_response template"
        assert isinstance(
            correct_output, str), "correct_output must be a string"

        if output is not None and isinstance(output, str) and len(output) > 1:
            output_c = output.lower().strip()
            # Remove surrounding quotes if they exist
            if (output_c.startswith('"') and output_c.endswith('"')) or \
                    (output_c.startswith("'") and output_c.endswith("'")):
                output_c = output_c[1:-1]  # Slice off the first and last char

            if is_correct:
                if output_c == correct_output.lower().strip():
                    return True
            else:
                if output_c != correct_output.lower().strip():
                    return True

        if raw_output is not None and not strict_output_verification:
            return verify_correctness_of_free_generative_output(raw_output, correct_output, is_correct)

        return False
    elif prompt_type == PromptType.GENERATIVE_MC:
        assert correct_output is not None, "correct_output must be provided for generative_mc template"
        assert isinstance(
            correct_output, str), "correct_output must be a string"

        output_c = output.lower().strip().replace("(", "").replace(")", "")
        correct_output_c = correct_output.lower().strip()

        if is_correct:
            return output_c == correct_output_c
        else:
            return output_c != correct_output_c
    else:
        raise NotImplementedError(f"Unknown prompt type: {prompt_type}")


def load_experiment_data(filepath: str) -> ExperimentResult:
    """
    Load the experiment data from a JSON file.

    Args:
        filepath (str): The path to the JSON file containing the experiment data.

    Returns:
        ExperimentResult: An object containing the loaded experiment data.
        The object contains the model name, inference tasks, and results.
        Each result contains the prompt and the outputs.
        The outputs are stored as a list of ResponseOutput objects.
        Each ResponseOutput object contains the responses, parsed responses, and iteration number.

    Raises:
        FileNotFoundError: If the specified file does not exist.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")

    with open(filepath, "r") as f:
        data = json.load(f)

    # Convert the data to the appropriate types
    inference_tasks = [InferenceTask.from_dict(
        task) for task in data["inference_tasks"]]
    results = []
    for result in data["results"]:
        prompt_dict = result["prompt"]

        # Conver the phase string to a Phase object
        phase = prompt_dict["phase"]
        if isinstance(prompt_dict["phase"], str):
            phase = Phase(phase)
            prompt_dict["phase"] = phase

        # Convert the prompt_type string to a PromptType object
        prompt_type = prompt_dict["prompt_type"]
        if isinstance(prompt_type, str):
            prompt_type = PromptType(prompt_type)
            prompt_dict["prompt_type"] = prompt_type

        # Create the prompt object
        if prompt_type == PromptType.DOUBLE_CRITIC or prompt_type == PromptType.DOUBLE_CRITIC_MC:
            prompt = VerificationPrompt(**prompt_dict)
        elif prompt_type == PromptType.GENERATIVE_FREE or prompt_type == PromptType.GENERATIVE_MC:
            prompt = GenerationPrompt(**prompt_dict)
        else:
            raise NotImplementedError(f"Unknown prompt type: {prompt_type}")

        response_outputs = []
        for output_dict in result["response_outputs"]:
            # Convert API verdict dictionaries (if present) to APIGradingOutput objects
            if "api_verdicts" in output_dict and output_dict["api_verdicts"] is not None:
                output_dict["api_verdicts"] = [APIGradingOutput(
                    **api_verdict) for api_verdict in output_dict["api_verdicts"]]

            response_output = ResponseOutput(**output_dict)
            response_outputs.append(response_output)
        results.append(ExperimentPromptResults(
            prompt=prompt, response_outputs=response_outputs))

    return ExperimentResult(
        model=data["model"],
        inference_tasks=inference_tasks,
        results=results
    )


@overload
def organize_experiment_data_by_iteration(
    filepath: Optional[str],
    experiment_results: Optional[ExperimentResult],
    return_experiment_results: Literal[False] = False
) -> dict[int, list[PromptParsedResults]]:
    ...


@overload
def organize_experiment_data_by_iteration(
    filepath: Optional[str],
    experiment_results: Optional[ExperimentResult],
    return_experiment_results: Literal[True] = True
) -> tuple[dict[int, list[PromptParsedResults]], ExperimentResult]:
    ...


def organize_experiment_data_by_iteration(
    filepath: Optional[str] = None,
    experiment_results: Optional[ExperimentResult] = None,
    return_experiment_results: bool = False
) -> dict[int, list[PromptParsedResults]] | tuple[dict[int, list[PromptParsedResults]], ExperimentResult]:
    """
    Organize the experiment data by iteration.

    Args:
        filepath (str): The path to the JSON file containing the experiment data.
        experiment_results (ExperimentResult): An object containing the loaded experiment data.
        return_experiment_results (bool): If True, return the experiment results.

    Returns:
        dict[int, list[PromptParsedResults]]: A dictionary where the keys are iteration numbers and the values are PromptParsedResults objects.
        Each PromptParsedResults object contains the prompt and the parsed responses for that iteration.
        If return_experiment_results is True, also return the experiment results.

    Raises:
        ValueError: If neither filepath nor experiment_results is provided.
    """

    if not filepath and not experiment_results:
        raise ValueError(
            "Either filepath or experiment_results must be provided")

    if filepath:
        experiment_results = load_experiment_data(filepath)

    if experiment_results is None:
        raise ValueError(
            "ExperimentResult is None. Please provide a valid filepath or experiment_results.")

    results_by_iteration = defaultdict(list)
    for prompt_results in experiment_results.results:
        prompt = prompt_results.prompt

        for response_output in prompt_results.response_outputs:
            iteration = response_output.iteration

            results_by_iteration[iteration].append(
                PromptParsedResults(prompt=prompt,
                                    parsed_responses=response_output.parsed_responses,
                                    api_verdicts=response_output.api_verdicts,
                                    responses=response_output.responses,
                                    char_lengths=response_output.char_lengths
                                    )
            )

    if return_experiment_results:
        return results_by_iteration, experiment_results
    else:
        return results_by_iteration
